services:
  nginx:
    image: nginx:1.25.3-alpine3.18-slim
    ports:
      - 8080:80
    volumes:
      - ..:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on: &depends
      - mariadb

  php:
    image: cirolosapio/php-fpm:8.1.27-alpine3.19-composer2.7.1-xdebug3.3.1-mysql-zip
    volumes:
      - ..:/var/www/html:cached
      - ~/.ssh:/home/php/.ssh:rw
      - ~/.composer:/home/php/.composer:rw
      - ~/.zsh_history:/home/php/.zsh_history:rw
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  mariadb:
    image: mariadb:11.3.2-jammy
    command: --default-authentication-plugin=mysql_native_password
    ports: [ 3306:3306 ]
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: laravel
    volumes:
      - mariadb:/var/lib/mysql:rw

volumes:
  mariadb:
